name: Generate ASCII Artwork

on:
  # push
  workflow_dispatch: 

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay Program
      run: sudo apt-get install cowsay -y

    - name: Execute Cowsay CMD
      run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt
    
    - name: Upload the Dragon text file
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text-file
        path: dragon.txt 

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1

    steps:
    - name : Download Dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file

    - name: Test File Exists
      run: grep -i "dragon" dragon.txt

  deploy_job_2:
    runs-on: ubuntu-latest
    needs: [test_job_2]
    steps:
    - name : Download Dragon text file
      uses: actions/download-artifact@v4
      with:
        name: dragon-text-file

    - name: Read File
      run: cat dragon.txt

    - name: Delploy
      run: echo Deploying...

